[build]
builder = "NIXPACKS"

[start]
cmd = "gunicorn backend_nc.wsgi:application --chdir backend_nc"

[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311Full"]

[phases.build]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install -r backend_nc/requirements.txt"
]
