# Generated by Django 5.1.7 on 2025-03-30 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_deteccion', models.DateField()),
                ('procedimiento_afectado', models.CharField(max_length=100)),
                ('origen', models.TextField()),
                ('descripcion', models.TextField()),
                ('estudio_causa', models.TextField(blank=True, null=True)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('firma_responsable', models.BooleanField(default=False)),
                ('motivo_cierre', models.TextField(blank=True, null=True)),
                ('evaluacion_eficacia', models.TextField(blank=True, null=True)),
                ('fecha_cierre_seguridad', models.DateField(blank=True, null=True)),
                ('validado_por_seguridad', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('correctiva', 'Correctiva'), ('preventiva', 'Preventiva')], max_length=20)),
                ('fecha_compromiso', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('evaluacion_eficacia', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('no_conformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='core.noconformidad')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.accion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
