# Generated by Django 5.1.7 on 2025-04-14 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeNoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_deteccion', models.DateField()),
                ('descripcion_nc', models.TextField()),
                ('documentacion_referencia', models.TextField(blank=True, null=True)),
                ('descripcion_situacion', models.TextField(blank=True, null=True)),
                ('criterio_nc', models.TextField()),
                ('causa_nc', models.TextField(blank=True, null=True)),
                ('clasificacion_deficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('acciones_inmediatas', models.TextField(blank=True, null=True)),
                ('necesita_accion_correctiva', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revisión'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('usuario_reporta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_reportados', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
