# Generated by Django 5.1.7 on 2025-04-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_informenoconformidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_apertura', models.DateField()),
                ('procedimiento_afectado', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('estudio_causa', models.TextField(blank=True, null=True)),
                ('clasificacion_deficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_1', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_responsable_1', models.BooleanField(default=False)),
                ('responsable_2', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_responsable_2', models.BooleanField(default=False)),
                ('evaluacion_eficacia', models.TextField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True, null=True)),
                ('fecha_cierre_seguridad', models.DateField(blank=True, null=True)),
                ('validado_por_seguridad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccionPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correctiva', 'Correctiva'), ('preventiva', 'Preventiva')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_compromiso', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='core.informeaccion')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.informeaccion')),
            ],
        ),
    ]
