# Generated by Django 5.1.7 on 2025-04-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_informeaccion_accionpropuesta_seguimientoaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='acciones_inmediatas',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='causa_nc',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='clasificacion_deficiencia',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='criterio_nc',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='descripcion_nc',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='descripcion_situacion',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='documentacion_referencia',
        ),
        migrations.RemoveField(
            model_name='informenoconformidad',
            name='necesita_accion_correctiva',
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='accion_asociada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='accion_efectiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='descripcion_verificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='detectado_por',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='evidencia_documental',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='fecha_verificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='firma_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='realizada_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='requisito_incumplido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='responsable_seguridad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='riesgo_asociado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='solucion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informenoconformidad',
            name='tratamiento_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informenoconformidad',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
