# Generated by Django 5.1.7 on 2025-05-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_informenoconformidad_acciones_inmediatas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeaccion',
            name='origen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
